discussion/urls.py
from django.urls import path

from . import views

app_name = 'discussion'

urlpatterns = [
    path('', views.index, name='index'),
    path('newpost/', views.new_post, name='new_post'),
    path('<slug:post>/', views.post_single, name='post_single'),
]

homepage/urls.py
from django.urls import path

from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.index, name='index'),
]

pajeet/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('question/', include('discussion.urls')),
]

discussion/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from mptt.models import MPTTModel, TreeForeignKey

class Post(models.Model):

    class NewManager(models.Manager):
        def get_queryset(self):
            return super().get_queryset() .filter(status='published')

    options = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length=250, unique=True)
    excerpt = models.TextField(null=True)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    publish = models.DateTimeField(default=timezone.now)
    author = models.CharField(max_length=50)
    content = models.TextField()
    status = models.CharField(max_length=10, choices=options, default='published')
    objects = models.Manager()  # default manager
    newmanager = NewManager()  # custom manager

    def get_absolute_url(self):
        return reverse('discussion:post_single', args=[self.slug])

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title


class Comment(MPTTModel):

    post = models.ForeignKey(Post,
                             on_delete=models.CASCADE,
                             related_name='comments')
    name = models.CharField(max_length=50)
    parent = TreeForeignKey('self', on_delete=models.CASCADE,
                            null=True, blank=True, related_name='children')
    email = models.EmailField()
    content = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    status = models.BooleanField(default=True)

    class MPTTMeta:
        order_insertion_by = ['publish']

    def __str__(self):
        return self.name

homepage/models.py
from django.db import models

# Create your models here.

discussion/forms.py
from django import forms
from .models import Comment, Post
from mptt.forms import TreeNodeChoiceField


class NewCommentForm(forms.ModelForm):
    parent = TreeNodeChoiceField(queryset=Comment.objects.all())

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['parent'].widget.attrs.update(
            {'class': 'd-none'})
        self.fields['parent'].label = ''
        self.fields['parent'].required = False

    class Meta:
        model = Comment
        fields = ('name', 'parent', 'email', 'content')

        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control mb-3', 'placeholder': 'Name'}),
            'email': forms.TextInput(attrs={'class': 'form-control mb-3', 'placeholder': 'E-mail'}),
            'content': forms.Textarea(attrs={'class': 'form-control mb-3', 'placeholder': 'Content'}),
        }

        labels = {
            'name': 'Name',
            'email': "E-mail",
            'content': 'Content',
        }

    def save(self, *args, **kwargs):
        Comment.objects.rebuild()
        return super(NewCommentForm, self).save(*args, **kwargs)

class PostForm(forms.ModelForm):
    title = forms.CharField(label="Judul",
                           widget=forms.TextInput(
                               attrs={
                                   "placeholder": "Judul",
                                   "class": "form-control",
                               }
                           )
                           )
    author = forms.CharField(label="Nama",
                           widget=forms.TextInput(
                               attrs={
                                   "placeholder": "Nama",
                                   "class": "form-control",
                               }
                           )
                           )
    excerpt = forms.CharField(label="Kelompok",
                           widget=forms.TextInput(
                               attrs={
                                   "placeholder": "Kelompok",
                                   "class": "form-control",
                               }
                           )
                           )
    content = forms.CharField(label="Pertanyaan",
                           widget=forms.Textarea(
                               attrs={
                                   "placeholder": "Pertanyaan",
                                   "class": "form-control",
                               }
                           )
                           )
    class Meta:
        model = Post
        fields = [
            'title',
            'author',
            'excerpt',
            'content',
        ]

discussion/views.py
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect
from .models import Post, Comment
from .forms import NewCommentForm, PostForm
from django.views.generic import ListView
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.template.defaultfilters import slugify

def index(request):
    all_posts = Post.newmanager.all()
    return render(request, 'index.html', {'posts': all_posts})

def post_single(request, post):

    post = get_object_or_404(Post, slug=post, status='published')

    allcomments = post.comments.filter(status=True)
    page = request.GET.get('page', 1)

    paginator = Paginator(allcomments, 10)
    try:
        comments = paginator.page(page)
    except PageNotAnInteger:
        comments = paginator.page(1)
    except EmptyPage:
        comments = paginator.page(paginator.num_pages)

    user_comment = None

    if request.method == 'POST':
        comment_form = NewCommentForm(request.POST)
        if comment_form.is_valid():
            user_comment = comment_form.save(commit=False)
            user_comment.post = post
            user_comment.save()
            return HttpResponseRedirect('/question/' + post.slug)
    else:
        comment_form = NewCommentForm()
    return render(request, 'single.html', {'post': post, 'comments':  user_comment, 'comments': comments, 'comment_form': comment_form, 'allcomments': allcomments, })

def new_post(request):
    form = PostForm(request.POST or None)
    if (form.is_valid() and request.method == 'POST'):
        post = form.save(commit=False)
        post.slug = slugify(post.title)
        post.save()
        return HttpResponseRedirect('/question/')
    context = {
        'form': form
    }
    return render(request, 'newpost.html', context)

homepage/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, "homepage/index.html")

discussion/templates/index.html
{% extends 'homepage/base.html' %}
{% block content %}
<h1 style="text-align: center; margin-top: 100px;">Discussion Forum</h1>
    <div class="album py-5 bg-light" style="height: 100vh;">
      <div class="container">
        <div class="row">
          {% for post in posts %}
          <div class="col-md-4">
            <a class="text-dark" href="{{post.get_absolute_url}}">
              <div class="card mb-4 box-shadow">
                <div class="card-body">
                  <p class="h4"">{{post.title|truncatechars:50}}</p>
                  <p class="lead card-text">{{post.excerpt|truncatechars:50}}</p>
                  <div class="d-flex justify-content-between align-items-center">
                    <small class="text-muted">{{post.publish|date:'d/m/Y'}} - {{ post.author }}</small>
                  </div>
                </div>
              </div>
            </a>
          </div>
          {% endfor %}
          <div class="container">
            <div class="row justify-content-center">
                <a class="btn btn-dark" href="newpost" role="button">Create new Post</a>
            </div>
          </div>
        </div>
      </div>
    </div>
<br>
    {% endblock %}

discussion/templates/newpost.html
{% extends 'homepage/base.html' %}

{% block content %}
<br>
<br>
<br>
<br>
<br>
<div class="container">
    <div class="row justify-content-center">
      <div class="col-8">
        <h2 class="featurette-heading"><b>Pertanyaan</b></h2>
        <hr class="mt-0 mb-4">
        <form method='POST'>
            {% csrf_token %}
            {{ form.as_p }}
            <br>
           <button type="submit" class="btn btn-dark">Submit</button>
           <a class="btn btn-dark" href="../">Back</a>
        </form>
        <br>
      </div>
    </div>
  </div>
<br>

{% endblock %}

discussion/templates/single.html
{% extends 'homepage/base.html' %}
{% load humanize %}

{% block content %}

<style>
  @media screen and (min-width: 600px) {
    .children form {
      margin-left: -48px;
      /* will touch very left side */
    }

    .children .children form {
      margin-left: -96px;
      /* will touch very left side */
    }
  }
</style>

<br>
<br>

<div class="container">
  <div class="row justify-content-md-center pt-5">

    <div class="col-md-7">
      <p class="h2">{{post.title}}</p>
    </div>
    <div class="col-md-7">
      <p class="text-justify" style="font-size: 20px;">{{post.content|safe}}</p>
    </div>
    <div class="col-md-7">

      {% with allcomments.count as total_comments %}
      <h5 class="lead">
        {{ total_comments }} comment{{ total_comments|pluralize }}
      </h5>
      {% endwith %}

      {% load mptt_tags %}

      <div>
        {% recursetree comments %}
        <div id="{{ node.id }}" class="my-2 p-2 rounded">
          <div class="d-flex justify-content-between"><b>{{ node.name }}</b><div></div>{{ node.publish|naturaltime }}</div>
          <div>{{ node.content }}</div>
          <hr>
          {% if node.level < 3 %}
          <button class="btn btn-light" onclick="myFunction({{ node.id }})">Reply</button>
          {% endif %}
        </div>
        {% if not node.is_leaf_node %}
        <div class="children pl-2 pl-md-5">
          {{ children }}
        </div>
        {% endif %}
        {% endrecursetree %}
      </div>

      <div class="py-4">
        <nav aria-label="Page navigation example">
          {% if comments.has_other_pages %}
          <ul class="pagination">
            {% if comments.has_previous %}
            <li class="page-item"><a class="page-link" href="?page={{ comments.previous_page_number }}">Previous</a>
            </li>
            {% else %}
            <li class="page-item disabled"><a class="page-link" href="#">Previous</a></li>
            {% endif %}
            {% for num in comments.paginator.page_range %}
            {% if comments.number == l %}
            <li class="page-item active"><span class="page-link">{{ num }} <span class="sr-only">(current)</span></span>
            </li>
            {% else %}
            <li><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
            {% endif %}
            {% endfor %}
            {% if comments.has_next %}
            <li class="page-item"><a class="page-link" href="?page={{ comments.next_page_number }}">Next</a></li>
            {% else %}
            <li class="page-item disabled"><a class="page-link" href="#">Next</a></li>
            {% endif %}
          </ul>
          {% endif %}
        </nav>
      </div>

      <button onclick="thatFunction()" class="btn btn-dark">Create new comment</button>

      <div id="thatDIV" style="display:none;">
        <form id="myForm" method="post">
          {{ comment_form.as_p }}
          {% csrf_token %}
          <button type="submit" class="btn btn-dark" >Submit</button>
        </form>
      </div>

    </div>
  </div>
</div>
<br>
<script>
  function thatFunction() {
    var x = document.getElementById("thatDIV");
  if (x.style.display === "none") {
    x.style.display = "block";
  } else {
    x.style.display = "none";
  }
  }  

  function formExit() {
    document.getElementById("newForm").remove();
  }

  function myFunction(id) {
    if (document.contains(document.getElementById("newForm"))) {
      document.getElementById("newForm").remove();
    }

    var d1 = document.getElementById(id);
    d1.insertAdjacentHTML('afterend',
      '<form id="newForm" class="form-insert py-2" method="post"> \
                <label for="id_name">Name:</label> \
                <input type="text" name="name" class="col-sm-12" maxlength="50" required="" id="id_name" placeholder="Name">\
                <select name="parent" class="d-none" id="id_parentt"> \
                <option value="' + id + '" selected="' + id + '"></option> \
                </select> \
                <label for="id_email">E-mail:</label> \
                <input type="text" name="email" class="col-sm-12" maxlength="254" required="" id="id_email" placeholder="E-mail"> \
                <label for="id_content">Content:</label> \
                <textarea name="content" cols="40" rows="5" class="form-control" required id="id_content" placeholder="Content"></textarea> \
                {% csrf_token %} \
                <br> \
                <button type="submit" class="btn btn-dark">Submit</button> <button type="button" class="btn btn-dark" onclick="formExit()"">Close</button> \
              </form>');

    //document.querySelector('#id_parentt [value="' + id + '"]').selected = true;
  }

  $('#myForm').trigger("reset");
</script>

{% endblock %}

homepage/templates/homepage/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- External CSS -->
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link rel="shortcut icon" type="image/JPG" href="{% static 'homepage/pic/pd-logo.JPG' %}">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    {% block meta %}
    {% endblock meta %}
  </head>
  <body>
      <nav class="navbar fixed-top navbar navbar-expand-lg navbar-dark" style="background-color:#62959A">
        <a href="#" class="navbar-brand">
            <!-- Logo Image -->
            <img src="{% static 'homepage/pic/pd-logo.JPG' %}" width="45" alt="" class="d-inline-block align-middle mr-2">
            <!-- Logo Text -->
            <span class="text-uppercase font-weight-bold">PAJEET's<span style="color:#F0AD4E"> DIARY</span></span>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
        <div class="collapse navbar-collapse" style="justify-content: center;" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'homepage:index' %}">HOME</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'discussion:index' %}">DISCUSSION</a>
                </li>
                
            </ul>
        </div>
    </nav>
  
    {% block content %}
    {% endblock %}
    <div class="footer-copyright text-center py-3" style="background-color: #62959A;">Ce Site-Web est de Pajeet</div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

homepage/templates/homepage/index.html
{% extends 'homepage/base.html' %}
{% load static %}

{% block meta %}
<title>Home</title>
{% endblock meta %}

{% block content %}
<div class="container" style="margin-top: 5%; margin-bottom: 5%;">
    <div class="row">
        <hr class="hr-rounded">
    </div>
    <div class="col-12">
        <h2 style="text-align: center;">HOME PAGE</h2>
    </div>
    <div id="kotak1" class="col-12">
        <div class="carousel-inner">
                <div class="carousel-item active">
                <div class="embed-responsive embed-responsive-4by3">
                    <iframe src="https://onedrive.live.com/embed?cid=AB18559D12CF84E3&resid=AB18559D12CF84E3%21852&authkey=ALSKsMKuwGZz6CU&em=2" width="402" height="327" frameborder="0" scrolling="no"></iframe>
                </div>
                </div>
        </div>
    </div>
</div>
{% endblock %}